### ISSUE TITLE
Generates too many fibers

### ISSUE THREAD

**Issue by soichih** [brain-life/app-AFQ_no-life#1]
I've run this app with ensemble track output. Compared to AFQ with LiFE, it's generating a lot more fibers for each tracts than it should.

*app-AFQ_no-life*
```
Tracts,FiberCount
Left Thalamic Radiation,5019
Right Thalamic Radiation,7924
Left Corticospinal,4696
Right Corticospinal,6457
Left Cingulum Cingulate,2710
Right Cingulum Cingulate,1672
Left Cingulum Hippocampus,1561
Right Cingulum Hippocampus,1463
Callosum Forceps Major,805
Callosum Forceps Minor,6367
Left IFOF,3477
Right IFOF,1389
Left ILF,1338
Right ILF,2398
Left SLF,11485
Right SLF,17314
Left Uncinate,1266
Right Uncinate,2129
Left Arcuate,5961
Right Arcuate,1991
```

*app-tractclassification*
```
Tracts,FiberCount
Left Thalamic Radiation,831
Right Thalamic Radiation,1519
Left Corticospinal,910
Right Corticospinal,1067
Left Cingulum Cingulate,632
Right Cingulum Cingulate,309
Left Cingulum Hippocampus,191
Right Cingulum Hippocampus,164
Callosum Forceps Major,42
Callosum Forceps Minor,914
Left IFOF,309
Right IFOF,148
Left ILF,225
Right ILF,342
Left SLF,3047
Right SLF,3663
Left Uncinate,205
Right Uncinate,307
Left Arcuate,807
Right Arcuate,386 
```

Maybe I shouldn't be running this app on ensemble track?

**Comment by kitchell** [comment]
according to dan: Life culls anywhere from 70 to 85 percent.  Thus you should expect a 3 to 6 x increase.

so I think the numbers are actually ok. it is only a problem if it is finding fibers outside of the tracts.

**Comment by soichih** [comment]
OK> "should expect a 3 to 6 x increase" 

The actual size of tracts directory however, is about 30 times larger (68M v.s 2000M). 68M by itself is probably too large to begin with, but 2000M is non-starter.

It seems that not only the number of fibers are greater, but for each fibers it is either much longer, or has more way-points - inflating the size of the tracts.json  (coordinates array seems to be x2-x3 times lager)

Do you know this is the case?

[life.1.gz](https://github.com/brain-life/app-AFQ_no-life/files/1391855/life.1.gz)
[nolife.1.gz](https://github.com/brain-life/app-AFQ_no-life/files/1391856/nolife.1.gz)

**Comment by kitchell** [comment]
this app now subsamples the tracts for the .json files to only include every third streamline. Should be able to visualize now.

**Comment by soichih** [comment]
@kitchell Thanks! It looks like tracts are about 1/3 of original counts.

Before > Right SLF,17314
Now > Right SLF,5888

However, 5888 is still way to high.. at least for my 1-yo laptop (XPS15) with 16G memory / GTX 1050 GPU. It seems to load the page barely, then it crashes... 

![screenshot from 2018-01-22 14-51-46](https://user-images.githubusercontent.com/923896/35241538-c6a6b4d4-ff84-11e7-86be-8aff500ae60a.png)

I believe the subsampling at ever third streamline has another issue, where the tract only has small number of tracts. In such case, we want to display *all* tracts without subsampling..

Can you update the sampling algorithm so that, it simply grabs the first 1000 tracts, and show all if there are less than 1000 tracts? I believe each tracts are more/less randomly distributed so grabbing the first 1000 tracts (instead of a proper sampling) should not affect how tracts are visualized.. Do you think that will not work?
