### ISSUE TITLE
Deprecate this repo

### ISSUE THREAD

**Issue by soichih** [brain-life/app-AFQ_no-life#2]
I believe we can deprecate this app by updating https://github.com/brain-life/app-tractclassification so that it can load track.tck if "track" input is specified instead of life input.

**Comment by soichih** [comment]
@kitchell I'd like to update app-tractclassification to have the similar product.json as this app, but I think what I really should do is to merge the functionality of this repo to app-tractclassification so that it can handle both LiFE and non-Life tract, and move the product.json code to app-tractclassification. Should I proceed?

**Comment by kitchell** [comment]
I think that is ok. i'm trying to think why it wouldn't be a good idea. it'd be nice to auto tag the output based on whether it came from a life or tck, but we don't do that now (the output looks the same whether it came from the no-life or life afq) and it works ok. 

how do optional input apps work with the pipeline rules? will that be a problem?

**Comment by soichih** [comment]
We will keep the existing App registrations for both Life and non-Life. They will just point at the same github repo. Each App can then set its own datatype tags. I just added "post_life" and "pre_life" (tags suggested by @francopestilli) on AFQ apps. 

Apart from the tagging issue, is there other reason why I shouldn't merge the repo? My goal is to re-use as much of the same code as possible - so that we don't have to maintain 2 separate code bases that does mostly the same thing.

**Comment by kitchell** [comment]
ohh! i see. I thought you were combining the apps as well. I don't think there is an issue with merging then.

**Comment by soichih** [comment]
I've updated app-tractclassification App to be able to handle both life and non-life (track) input. This App can be deprecated now.
