### ISSUE TITLE
Not enough input arguments.

### ISSUE THREAD

**Issue by soichih** [brain-life/app-AFQ_no-life#4]
I've recompiled this app using the latest vistasoft. 

I am now seeing following error message when I run it.

```
Not enough input arguments.

Error in nanmean (line 7)


Error in AFQ_SegmentFiberGroups (line 267)


Error in main (line 28)
```

@kitchell @DanNBullock Can you help me troubleshoot this?

**Comment by francopestilli** [comment]
@soichih are you using a newer version of matlab? it looks n=like nanmean.m requires different inputs.

**Comment by soichih** [comment]
We've been using matlab/2017a for a while now. I believe we've built the previous version of this app with 2017a and worked fine, but maybe I am wrong? @kitchell Do you know if I need to use 2016 for this App?

This App is using Lindsey's patched version of AFQ here 

> /N/u/kitchell/Karst/Applications/AFQ 

Due to [this issue](https://github.com/yeatmanlab/AFQ/issues/24)

**Comment by soichih** [comment]
I believe this issue is now resolved..
