### ISSUE TITLE
Possible error in CST_roi2_L.nii.gz and  CST_roi2_R.nii.gz

### ISSUE THREAD

**Issue by giulia-berto** [brain-life/app-AFQ_no-life#5]
Hi, it seems to me that the ROI templates `app-AFQ_no-life/templates/MNI_JHU_tracts_ROIs/CST_roi2_L.nii.gz and CST_roi2_R.nii.gz` are wrong because they both include the left and right ROIs instead of just one.

**Comment by kitchell** [comment]
I believe the templates were copied from AFQ directly, so we can use them
in the compiled code.

**Comment by francopestilli** [comment]
@giulia-berto thanks for digging this out. Are L and R coded with different numbers (Say 1 and 2 or 0 and 1, or similar)?

**Comment by giulia-berto** [comment]
No, it's a binary mask, but instead of 1s, the positive values are 0.5, on both sides. I think the ROI should be split into two.

**Comment by francopestilli** [comment]
Hi Giulia

I think the code we use takes care of removing the controlateral ROI

**Comment by soichih** [comment]
This App is now deprecated by https://github.com/brain-life/app-tractclassification 

@giulia-berto Are you still having this issue? If so, could you re-submit this issue on above app?

Thanks!
